### ISSUE TITLE
 org.pcap4j.core.PcapNativeException: path_to_pcap: No such file or directory

### ISSUE THREAD

**Issue by wolferl42195** [WojciechZankowski/iextrading4j-hist#10]
Hi,
Thanks for the project. I try to get it run.

I just installed it and after some problems with the Npcap I got the output:
13:49:17.765 [main] INFO org.pcap4j.core.NativeMappings - Pcap4J successfully loaded a native pcap library: Npcap version 0.99-r7, based on libpcap version 1.8.1
Exception in thread "main" org.pcap4j.core.PcapNativeException: path_to_pcap: No such file or directory
	at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:241)
	at pl.zankowski.iextrading4j.hist.samples.TOPSSample.readTOPSsample(TOPSSample.java:21)
	at pl.zankowski.iextrading4j.hist.samples.TOPSSample.main(TOPSSample.java:17)

Then I configured the parameter to "C:\\Program Files (x86)\\Nmap" and then I got  
Exception in thread "main" org.pcap4j.core.PcapNativeException: C:\Program Files (x86)\Nmap: Permission denied
	at org.pcap4j.core.Pcaps.openOffline(Pcaps.java:241)
	at pl.zankowski.iextrading4j.hist.samples.TOPSSample.readTOPSsample(TOPSSample.java:20)
	at pl.zankowski.iextrading4j.hist.samples.TOPSSample.main(TOPSSample.java:16)

I set the Nmap directory to allow access, but this I get this exception. 

Thanks for help

**Comment by WojciechZankowski** [comment]
Hey,


As 'path_to_pcap' you need to provide path to PCAP file with market data. You can download those files from IEX Trading site:

https://iextrading.com/trading/market-data/

For example:

``` D:\IEX\TOPS\20180629_IEXTP1_TOPS1.6.pcap ```



Cheers,

Wojtek

**Comment by wolferl42195** [comment]
Thanks works now!
